model:                    # architecture details
    type: regnetx_600m       # model name
    kwargs:
        num_classes: 1000
    path: /mnt/lustre/weixiuying/model_zoo/spring_regnetx_600m.pth
data:
    path: /mnt/lustre/share/ImageNet-Pytorch/
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005