extra_prepare_dict:
    extra_qconfig_dict:
        w_observer: MinMaxObserver
        a_observer: EMAMinMaxObserver
        w_fakequantize: FixedFakeQuantize
        a_fakequantize: FixedFakeQuantize
        w_qscheme:
            bit: 8
            symmetry: False
            per_channel: True
            pot_scale: False
        a_qscheme:
            bit: 8
            symmetry: False
            per_channel: False
            pot_scale: False
quantize:
    quantize_type: ptq # support ptq or qat
    cali_batchsize: 16
model:                    # architecture details
    type: resnet50        # model name
    kwargs:
        num_classes: 1000
    path: /mnt/lustre/weixiuying/model_zoo/resnet50_imagenet.pth.tar
data:
    path: /mnt/lustre/share/ImageNet-Pytorch/
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005